[package]
name = "progrem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
clap = {version = "4", features = ["derive"]}
map-macro = "0.2.5"
color-print = "0.3.4"